
CREATE VIEW VW_RESULTADO_OPERACAO
AS
SELECT	ISNULL(ORD_VENDA.DAT_CRIACAO,ORD_COMPRA.DAT_CRIACAO) DAT_ORDEM, ORD_COMPRA.VLR_INVESTIDO, ORD_VENDA.QTD_EXECUTADA * ORD_VENDA.VLR_MEDIO_EXECUTADO - ORD_VENDA.VLR_TAXA VLR_RECEBIDO, ISNULL(ROUND(ORD_VENDA.VLR_TAXA/(ORD_VENDA.QTD_EXECUTADA * ORD_VENDA.VLR_MEDIO_EXECUTADO),3),0) + ORD_COMPRA.PCT_TAXA PCT_TAXA_TOTAL
FROM	TB_MINHAS_ORDENS ORD_VENDA RIGHT JOIN(
										SELECT	C.IDT_ORDEM, C.QTD_EXECUTADA * C.VLR_MEDIO_EXECUTADO VLR_INVESTIDO, ROUND(C.VLR_TAXA/C.QTD_EXECUTADA,3) PCT_TAXA, MIN(V.DAT_CRIACAO) DAT_CRIACAO
										FROM	TB_MINHAS_ORDENS C INNER JOIN TB_MINHAS_ORDENS V
													ON(V.DAT_CRIACAO >C.DAT_CRIACAO)
										WHERE	C.IDT_TIPO_ORDEM = 'C'
										AND		V.IDT_TIPO_ORDEM = 'V'
										AND		C.IDT_STATUS = 4
										AND 	V.IDT_STATUS = 4
										GROUP BY C.IDT_ORDEM,C.VLR_MEDIO_EXECUTADO, C.QTD_EXECUTADA, C.VLR_TAXA
										) ORD_COMPRA
			ON( ORD_VENDA.DAT_CRIACAO = ORD_COMPRA.DAT_CRIACAO)
