CREATE VIEW VW_CONSULTAS_POR_HORA_BITSTAMP
AS
SELECT	C.*
FROM	(
		SELECT	DAT.DAT_BASE, MAX(CON.idt_consulta) idt_consulta
		FROM	(
				SELECT	DISTINCT DATEADD(HOUR, HOR.HORA,CONVERT(DATETIME, CONVERT(VARCHAR(10),DAT.dat_consulta,103),103)) DAT_BASE
				FROM	TB_CONSULTA_BITSTAMP DAT INNER JOIN SIS_TB_HORAS HOR
							ON(1=1)
				)  DAT INNER JOIN TB_CONSULTA_BITSTAMP CON
					ON(	CON.dat_consulta <= DAT.DAT_BASE)
		GROUP BY DAT.DAT_BASE
		) D INNER JOIN TB_CONSULTA_BITSTAMP  C
			ON(	C.idt_consulta = D.idt_consulta)
UNION
SELECT	C.*
FROM	TB_CONSULTA_BITSTAMP C INNER JOIN ( SELECT MAX(IDT_CONSULTA) IDT_CONSULTA FROM TB_CONSULTA_BITSTAMP) MAX_CON
			ON(MAX_CON.IDT_CONSULTA = C.idt_consulta)