CREATE VIEW VW_CENARIO_CURTO
AS
SELECT	DADOS.idt_consulta,
		CASE WHEN DADOS.vlr_compra < VLR_MED_COMPRA THEN 'CAINDO' 
			 WHEN DADOS.vlr_compra > VLR_MED_COMPRA THEN 'SUBINDO' 
			 ELSE 'ESTÁVEL' END CENARIO_COMPRA,
		CASE WHEN DADOS.vlr_venda < VLR_MED_VENDA THEN 'CAINDO' 
			 WHEN DADOS.vlr_venda > VLR_MED_VENDA THEN 'SUBINDO' 
			 ELSE 'ESTÁVEL' END CENARIO_VENDA
FROM	(
		SELECT	C1.idt_consulta,
				(C1.vlr_compra - CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_compra),6))) + (ROUND(CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_compra),6))/500,0)	*500) vlr_compra,
				(C1.vlr_venda - CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_venda),6))) + (ROUND(CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_venda),6))/500,0)	*500) vlr_venda,
				AVG((C2.vlr_compra - CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C2.vlr_compra),6))) + (ROUND(CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C2.vlr_compra),6))/500,0)	*500)) VLR_MED_COMPRA,
				AVG((C2.vlr_venda - CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C2.vlr_venda),6))) + (ROUND(CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C2.vlr_venda),6))/500,0)	*500)) VLR_MED_VENDA
		FROM	TB_CONSULTA C1 INNER 
		JOIN	TB_CONSULTA C2
					ON(C2.idt_consulta BETWEEN C1.idt_consulta-(250-1) AND C1.idt_consulta)
		GROUP BY C1.idt_consulta,
				 (C1.vlr_compra - CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_compra),6))) + (ROUND(CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_compra),6))/500,0)	*500),
				 (C1.vlr_venda - CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_venda),6))) + (ROUND(CONVERT(DECIMAL(16,2),RIGHT(CONVERT(VARCHAR,C1.vlr_venda),6))/500,0)	*500)
)DADOS