CREATE VIEW VW_ESTATISTICAS_3_CONSULTA_LIVRO
AS
SELECT	ATUAL.idt_consulta,
		ATUAL.vlr_compra,
		ATUAL.vlr_venda,
		ATUAL.QTD_COMPRA_LIVRO,
		ATUAL.QTD_VENDA_LIVRO,
		PAR.qtd_registros_anterior,
		ISNULL(ATUAL.vlr_compra/ANTERIOR.vlr_compra-1,0) EVOL_VLR_COMPRA,
		ISNULL(ATUAL.vlr_venda/ANTERIOR.vlr_venda-1,0) EVOL_VLR_VENDA,
		ISNULL(ATUAL.vlr_volume/ANTERIOR.vlr_volume-1,0) EVOL_VLR_VOLUME,
		ISNULL(ATUAL.QTD_COMPRA_LIVRO/ANTERIOR.QTD_COMPRA_LIVRO-1,0) EVOL_QTD_COMPRA_LIVRO,
		ISNULL(ATUAL.QTD_VENDA_LIVRO/ANTERIOR.QTD_VENDA_LIVRO-1,0) EVOL_QTD_VENDA_LIVRO,
		ISNULL(ATUAL.MEDIO_COMPRA_LIVRO/ANTERIOR.MEDIO_COMPRA_LIVRO-1,0) EVOL_MEDIO_COMPRA_LIVRO,
		ISNULL(ATUAL.MEDIO_VENDA_LIVRO/ANTERIOR.MEDIO_VENDA_LIVRO-1,0) EVOL_MEDIO_VENDA_LIVRO,
		ISNULL(ATUAL.MINIMO_COMPRA_LIVRO/ANTERIOR.MINIMO_COMPRA_LIVRO-1,0) EVOL_MIN_COMPRA_LIVRO,
		ISNULL(ATUAL.MAXIMO_VENDA_LIVRO/ANTERIOR.MAXIMO_VENDA_LIVRO-1,0) EVOL_MAX_VENDA_LIVRO
FROM	VW_ESTATISTICAS_2_CONSULTA ATUAL LEFT JOIN VW_ESTATISTICAS_2_CONSULTA ANTERIOR
			ON(	ANTERIOR.idt_consulta = ATUAL.idt_consulta-1)
JOIN	TB_PARAMETROS PAR
			ON( 1=1)