DELETE	TB_OPERACAO 
DELETE  TB_MINHAS_ORDENS


DECLARE @IDT_CONSULTA INT
DECLARE @MRC_OPERAR_O CHAR(1)
DECLARE @VLR_LIMITE_O DECIMAL(18,5)
DECLARE @MRC_AGUARDAR_O CHAR(1)


DECLARE @OPERACAO CHAR(1)
DECLARE @VLR_CARTEIRA DECIMAL(18,5)
DECLARE @IDT_ORDEM INT
DECLARE @DAT_ATUAL DATETIME
DECLARE @QTD_MOEDA  DECIMAL(18,5)
DECLARE @VLR_TAXA  DECIMAL(18,5)


SET @VLR_CARTEIRA = 1000
SET @QTD_MOEDA = 0


DECLARE CR CURSOR FOR
SELECT IDT_CONSULTA, dat_consulta
FROM TB_CONSULTA
ORDER BY idt_consulta
OPEN CR

FETCH CR INTO @IDT_CONSULTA, @DAT_ATUAL

WHILE @@FETCH_STATUS = 0
 BEGIN

	SET @MRC_OPERAR_O =NULL
	SET @VLR_LIMITE_O = NULL
	SET @MRC_AGUARDAR_O = NULL


	SELECT	@OPERACAO = O.IDT_TIPO_ORDEM 
	FROM	TB_MINHAS_ORDENS O INNER JOIN 
			(
			SELECT	MAX(DAT_CRIACAO) DAT_CRIACAO
			FROM	TB_MINHAS_ORDENS
			) D
				ON(	D.DAT_CRIACAO = O.DAT_CRIACAO)


	IF(@OPERACAO IS NULL OR @OPERACAO = 'V')
		EXEC SP_ANALISAR_COMPRA_TESTE @IDT_CONSULTA,@MRC_OPERAR = @MRC_OPERAR_O OUTPUT, @VLR_LIMITE = @VLR_LIMITE_O OUTPUT, @MRC_AGUARDAR = @MRC_AGUARDAR_O OUTPUT
	ELSE
		EXEC SP_ANALISAR_VENDA_TESTE @IDT_CONSULTA,@MRC_OPERAR = @MRC_OPERAR_O OUTPUT, @VLR_LIMITE = @VLR_LIMITE_O OUTPUT, @MRC_AGUARDAR = @MRC_AGUARDAR_O OUTPUT
	 
	 IF (@MRC_OPERAR_O = 'S')
	  BEGIN
			SELECT	@IDT_ORDEM = ISNULL(MAX(IDT_ORDEM),0) + 1
		FROM	TB_MINHAS_ORDENS
	
		--//COMPRANDO
		IF(@OPERACAO IS NULL OR @OPERACAO = 'V')
		 BEGIN

			SET @QTD_MOEDA = @VLR_CARTEIRA / @VLR_LIMITE_O
			SET @VLR_TAXA = @QTD_MOEDA*0.003
			SET @VLR_CARTEIRA = 0
			
			INSERT INTO TB_MINHAS_ORDENS VALUES(@IDT_ORDEM, 'C',4,@DAT_ATUAL,@DAT_ATUAL,@IDT_CONSULTA,@VLR_LIMITE_O,@QTD_MOEDA,@QTD_MOEDA,@VLR_LIMITE_O, @VLR_TAXA, @MRC_AGUARDAR_O)
			
			SET @QTD_MOEDA = @QTD_MOEDA - @VLR_TAXA
		 END
		--//VENDENDO
		ELSE
		 BEGIN

			SET @VLR_CARTEIRA = @QTD_MOEDA * @VLR_LIMITE_O
			SET @VLR_TAXA = @VLR_CARTEIRA*0.003

			INSERT INTO TB_MINHAS_ORDENS VALUES(@IDT_ORDEM, 'V',4,@DAT_ATUAL,@DAT_ATUAL,@IDT_CONSULTA,@VLR_LIMITE_O,@QTD_MOEDA,@QTD_MOEDA,@VLR_LIMITE_O, @VLR_TAXA, @MRC_AGUARDAR_O)	
			
			SET @VLR_CARTEIRA = @VLR_CARTEIRA - @VLR_TAXA

		 END 

	  END

	  

	FETCH CR INTO @IDT_CONSULTA, @DAT_ATUAL
 END

CLOSE CR
DEALLOCATE CR

SELECT	* FROM TB_MINHAS_ORDENS
