DECLARE @IDT_CONSULTA INT
DECLARE @MRC_OPERAR CHAR(1)
DECLARE @VLR_COMPRA DECIMAL(18,5)
DECLARE @VLR_VENDA DECIMAL(18,5)
DECLARE @VLR_MAXIMO DECIMAL(18,5)
DECLARE @VLR_MINIMO DECIMAL(18,5)

DECLARE @VLR_DIF_MAX_MIN DECIMAL(18,5)
DECLARE @VLR_CARTEIRA DECIMAL(18,5)
DECLARE @VLR_INVESTIDO DECIMAL(18,5)
DECLARE @QTD_BITCOINS DECIMAL(18,5)
DECLARE @PCT_TAXA DECIMAL(18,5)
DECLARE @PCT_RENDIMENTO DECIMAL(18,5)
DECLARE @VLR_SIMULADO_VENDA DECIMAL(18,5)


SET @VLR_CARTEIRA = 1000
SET @VLR_INVESTIDO = 0
SET @QTD_BITCOINS = 0
SET @PCT_TAXA = 0.003
SET @PCT_RENDIMENTO = 0.02
SET @VLR_SIMULADO_VENDA = 0


DECLARE CR CURSOR FOR
SELECT IDT_CONSULTA, vlr_compra, vlr_venda, vlr_maximo, vlr_minimo
FROM TB_CONSULTA

OPEN CR

FETCH CR INTO @IDT_CONSULTA, @VLR_COMPRA,@VLR_VENDA, @VLR_MAXIMO, @VLR_MINIMO

WHILE @@FETCH_STATUS = 0
 BEGIN
	
	--PROCESSO DE COMPRA
	IF(@VLR_CARTEIRA > 0)
	BEGIN
		
		SET @VLR_DIF_MAX_MIN = @VLR_MAXIMO - @VLR_MINIMO
		SET @PCT_RENDIMENTO = (@VLR_DIF_MAX_MIN/@VLR_MAXIMO)/5
		
		SELECT	@MRC_OPERAR = CASE WHEN (
											DIF_COMPRA_X_VENDA <= TB_PARAMETROS.vlr_dif_compra_x_venda AND
											TENDENCIA_MEDIA_COMPRA = 'DESCENDO' AND
											TENDENCIA_MINIMA_COMPRA = 'DESCENDO' AND
											TENDENCIA_MEDIA_VENDA = 'SUBINDO' AND
											MEDIA_VLR_VENDA BETWEEN ABS(TB_PARAMETROS.pct_define_estabilidade)*-1 AND ABS(TB_PARAMETROS.pct_define_estabilidade) AND
											QTD_VENDA_LIVRO >  QTD_COMPRA_LIVRO AND
											DISTANCIA_MAXIMO < TB_PARAMETROS.pct_ditancia_compra_max
										) THEN 'S' ELSE 'N' END 
		FROM	VW_ESTATISTICAS_COMPRA JOIN TB_PARAMETROS 
					ON(1=1)
		WHERE	IDT_CONSULTA = @IDT_CONSULTA

		IF(@MRC_OPERAR = 'S' AND @VLR_DIF_MAX_MIN > 3000)
		 BEGIN
			SET @QTD_BITCOINS = (@VLR_CARTEIRA/@VLR_COMPRA) - (@VLR_CARTEIRA/@VLR_COMPRA*@PCT_TAXA)
			SET @VLR_INVESTIDO = @VLR_CARTEIRA
			SET @VLR_CARTEIRA = 0
			SELECT 'COMPRA', @IDT_CONSULTA, @VLR_COMPRA
		 END
	 END
	--PROCESSO DE VENDA
	ELSE
	 BEGIN
		SET @VLR_SIMULADO_VENDA = (@QTD_BITCOINS*@VLR_VENDA) - (@QTD_BITCOINS*@VLR_VENDA*@PCT_TAXA)

		IF(@VLR_SIMULADO_VENDA/@VLR_INVESTIDO-1 >@PCT_RENDIMENTO)
		 BEGIN
			SET @VLR_CARTEIRA = @VLR_SIMULADO_VENDA
			SET @QTD_BITCOINS = 0
			SET @VLR_INVESTIDO = 0
			SELECT 'VENDA', @IDT_CONSULTA, @VLR_VENDA
		 END
	 END

	FETCH CR INTO @IDT_CONSULTA,@VLR_COMPRA,@VLR_VENDA, @VLR_MAXIMO, @VLR_MINIMO
  END

  	 SELECT @VLR_CARTEIRA, @QTD_BITCOINS

CLOSE CR
DEALLOCATE CR




/*
declare @cont int
declare @idt_registro int

declare cr cursor for
select	idt_registro
from	TB_LIVRO_ORDENS
order by idt_registro
open cr

set @cont = 1

fetch cr into @idt_registro
while @@FETCH_STATUS=0
 begin
	
	if(@cont > 20)
	begin
		update TB_LIVRO_ORDENS
		set	cod_tipo_ordem = 'V'
		where idt_registro = @idt_registro
	end

	SET @CONT = @CONT + 1

	IF(@CONT > 40) SET @cont =1

	fetch cr into @idt_registro
 end
close cr
deallocate cr



*/